# Generated by Django 2.1.3 on 2019-03-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190315_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnet',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='carnet',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Culture',
        ),
        migrations.RemoveField(
            model_name='memoire',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='maladie',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Carnet',
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='Maladie',
        ),
        migrations.DeleteModel(
            name='Memoire',
        ),
        migrations.DeleteModel(
            name='Plante',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
