# Generated by Django 2.1.3 on 2019-03-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190315_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedecineNaturelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('contenu', models.CharField(max_length=500)),
                ('date_pubication', models.DateTimeField(blank=True, null=True)),
                ('feedback_sante', models.IntegerField(default=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='plante',
            name='maladie',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Plante',
        ),
    ]
