# Generated by Django 2.1.3 on 2019-03-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190315_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecinenaturelle',
            name='contenu',
            field=models.TextField(max_length=500),
        ),
    ]
