# Generated by Django 2.1.3 on 2019-03-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20190315_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='contenu',
            field=models.TextField(max_length=150000),
        ),
    ]
