# Generated by Django 2.1.3 on 2019-03-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_premiersoins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiersoins',
            name='contenu',
            field=models.TextField(max_length=15000),
        ),
    ]
