# Generated by Django 2.1.3 on 2019-03-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190316_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicomedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('description', models.TextField(max_length=15000)),
            ],
        ),
    ]
